"""
Write the trial-site registry the website's map and location selector read.

    cd backend && uv run --group ml python -m scripts.export_trial_sites

Reads the committed challenge inventory (ml/data/challenge/: sites, plots, usable images,
acquisition dates) and writes

    backend/data/trial_sites.json   served by GET /api/sites (live availability added there)
    src/mock/trialSites.ts          the same list for the demo build (no API)

Every fact comes from the inventory. "Imagery available" means the challenge set holds
usable plot images for that site and modality, not that a pass was scheduled: Missouri
Valley and Scottsbluff have satellite acquisition dates but no plot images. Rerun after
the inventory changes (`python -m soilsignal_ml challenge`).
"""

import json
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

BACKEND = Path(__file__).resolve().parent.parent
CHALLENGE = BACKEND.parent / "ml" / "data" / "challenge"
OUT_JSON = BACKEND / "data" / "trial_sites.json"
OUT_TS = BACKEND.parent / "src" / "mock" / "trialSites.ts"

# The ground-truth spelling is the site's id everywhere in the data (weather library,
# plots, models). Only the label people read differs.
DISPLAY_NAMES = {"MOValley": "Missouri Valley"}
STATE_NAMES = {"IA": "Iowa", "NE": "Nebraska"}

TS_HEADER = """/**
 * The five SyDAg26 trial sites, for the demo build (which has no API).
 * Generated by backend/scripts/export_trial_sites.py; do not edit by hand.
 * API mode reads the same list from GET /api/sites, with live availability added.
 */

import type { TrialSite } from '../types/sites';

export const TRIAL_SITES: TrialSite[] = """


def _dates(values: pd.Series) -> list[str]:
    return sorted({pd.Timestamp(v).date().isoformat() for v in values.dropna()})


def _imagery(
    images: pd.DataFrame, acquisitions: pd.DataFrame, site: str, year: int, modality: str
) -> dict:
    acq = acquisitions[
        (acquisitions["site_id"] == site)
        & (acquisitions["year"] == year)
        & (acquisitions["modality"] == modality)
    ]
    imgs = images[(images["site_id"] == site) & (images["modality"] == modality)]
    imgs = imgs[pd.to_datetime(imgs["date"]).dt.year == year]
    dates = _dates(acq["date"])
    return {
        "acquisitions": len(dates),
        "acquisition_dates": dates,
        "plot_images": int(len(imgs)),
        "plots_imaged": int(imgs["plot_id"].nunique()),
    }


def build() -> list[dict]:
    sites = pd.read_parquet(CHALLENGE / "sites.parquet")
    plots = pd.read_parquet(CHALLENGE / "plots.parquet")
    images = pd.read_parquet(CHALLENGE / "images.parquet")
    acquisitions = pd.read_parquet(CHALLENGE / "acquisition_dates.parquet")

    out = []
    # Only sites with ground-truth plots are trial sites (the imagery calendar also lists
    # NorthPlatte, which has no plots in the challenge set).
    for row in sites.sort_values("site_id").itertuples():
        site_plots = plots[plots["site_id"] == row.site_id]
        seasons = []
        for year, season_plots in site_plots.groupby("year"):
            year = int(year)
            seasons.append(
                {
                    "year": year,
                    "planting_dates": _dates(season_plots["planting_date"]),
                    "plots": int(len(season_plots)),
                    "plots_with_yield": int(season_plots["final_yield"].notna().sum()),
                    "hybrids": int(season_plots["genotype"].nunique()),
                    "satellite": _imagery(images, acquisitions, row.site_id, year, "satellite"),
                    "uav": _imagery(images, acquisitions, row.site_id, year, "uav"),
                }
            )
        out.append(
            {
                "id": row.site_id,
                "name": DISPLAY_NAMES.get(row.site_id, row.name),
                "state": row.state,
                "state_name": STATE_NAMES.get(row.state, row.state),
                "latitude": round(float(row.latitude), 6),
                "longitude": round(float(row.longitude), 6),
                "coordinate_source": row.coord_source,
                "crop": "Maize",
                "irrigated": bool(row.irrigated),
                "seasons": seasons,
            }
        )
    return out


def _camel(value):
    if isinstance(value, dict):
        return {
            k.split("_")[0] + "".join(p.title() for p in k.split("_")[1:]): _camel(v)
            for k, v in value.items()
        }
    if isinstance(value, list):
        return [_camel(v) for v in value]
    return value


def main() -> None:
    sites = build()
    document = {
        "source": "SyDAg26 challenge inventory (ml/data/challenge/)",
        "generated": datetime.now(UTC).replace(microsecond=0).isoformat(),
        "sites": sites,
    }
    OUT_JSON.write_text(json.dumps(document, indent=2) + "\n")
    OUT_TS.write_text(TS_HEADER + json.dumps(_camel(sites), indent=2) + ";\n")
    for s in sites:
        season = s["seasons"][0]
        print(
            f"{s['name']:<16} {s['state']} plots {season['plots']:>4}  "
            f"satellite images {season['satellite']['plot_images']:>4}  "
            f"UAV images {season['uav']['plot_images']:>4}"
        )
    print(f"wrote {OUT_JSON.relative_to(BACKEND.parent)} and {OUT_TS.relative_to(BACKEND.parent)}")


if __name__ == "__main__":
    main()
