"""
Fetch public data (soil, weather, county yields) for every demo field and write
it to src/mock/contextSnapshot.ts, which the dashboard shows in demo mode.
Running it also warms the backend cache.

    cd backend && uv run python -m scripts.snapshot_context

Rerun after changing a field's coordinates or forecast dates in src/mock/fieldsData.ts
(and `npm run export:mock`).
"""

import json
from datetime import date
from pathlib import Path

from app.config import get_settings
from app.context.cache import get_context_cache
from app.context.http import get_http_client
from app.context.service import LocationContextService

BACKEND = Path(__file__).resolve().parent.parent
FIELDS = BACKEND / "data" / "mock" / "fields.json"
OUT = BACKEND.parent / "src" / "mock" / "contextSnapshot.ts"

HEADER = """/**
 * Public data for the demo fields: soil from USDA NRCS SSURGO, weather from NOAA
 * NCEI (GHCN-Daily) and, when a key is configured, county yields from USDA NASS.
 * Generated by backend/scripts/snapshot_context.py; do not edit by hand.
 * Demo mode shows this snapshot instead of calling /api/context/all.
 */

import type { LocationContext } from '../types/agricultural';

export const CONTEXT_SNAPSHOT: Record<string, LocationContext> = """


def main() -> None:
    service = LocationContextService(get_http_client(), get_context_cache(), get_settings())
    snapshot = {}
    for forecast in json.loads(FIELDS.read_text()):
        field = forecast["field"]
        dates = [date.fromisoformat(s["date"]) for s in forecast["snapshots"]]
        context = service.location_context(field["latitude"], field["longitude"], dates)
        snapshot[field["id"]] = context.model_dump(mode="json", by_alias=True)
        print(
            f"{field['id']:12} soil={context.soil.status:13} weather={context.weather.status:13}"
            f" yields={context.yield_history.status}"
        )
    OUT.write_text(HEADER + json.dumps(snapshot, indent=2) + ";\n")
    print(f"wrote {OUT.relative_to(BACKEND.parent)}")


if __name__ == "__main__":
    main()
