/**
 * Public data for the demo fields: soil from USDA NRCS SSURGO, weather from NOAA
 * NCEI (GHCN-Daily) and, when a key is configured, county yields from USDA NASS.
 * Generated by backend/scripts/snapshot_context.py; do not edit by hand.
 * Demo mode shows this snapshot instead of calling /api/context/all.
 */

import type { LocationContext } from '../types/agricultural';

export const CONTEXT_SNAPSHOT: Record<string, LocationContext> = {
  "purdue-104": {
    "latitude": 40.4883,
    "longitude": -86.9982,
    "county": {
      "name": "Tippecanoe County",
      "stateCode": "IN",
      "stateName": "Indiana",
      "fips": "18157"
    },
    "soil": {
      "status": "ok",
      "data": {
        "mapUnitKey": "163904",
        "mapUnitName": "Chalmers silty clay loam",
        "series": "Chalmers",
        "componentPercent": 100.0,
        "taxonomicClass": "Fine-silty, mixed, superactive, mesic Typic Endoaquolls",
        "texture": "Silty clay loam",
        "drainage": "Poorly drained",
        "hydrologicGroup": "B/D",
        "availableWaterCapacity": 0.196,
        "availableWaterStorageCm": 19.6,
        "availableWaterClass": "High",
        "organicMatter": 4.5,
        "ph": 6.7,
        "rootZoneDepthCm": 152.0,
        "slopePercent": 0.5,
        "source": "USDA NRCS SSURGO",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "weather": {
      "status": "ok",
      "data": {
        "station": {
          "id": "USC00129430",
          "name": "West Lafayette 6 NW, IN",
          "latitude": 40.475,
          "longitude": -86.9919,
          "distanceKm": 1.6
        },
        "summaries": [
          {
            "asOf": "2026-05-30",
            "observedThrough": "2026-05-30",
            "rainfallLast7DaysMm": 3.8,
            "rainfallLast30DaysMm": 64.5,
            "avgTempLast30DaysF": 61.6,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 388.0,
            "heatDays": 0,
            "longestDrySpellDays": 3,
            "dataCompleteness": 0.97
          },
          {
            "asOf": "2026-06-15",
            "observedThrough": "2026-06-15",
            "rainfallLast7DaysMm": 85.6,
            "rainfallLast30DaysMm": 152.1,
            "avgTempLast30DaysF": 72.1,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 760.0,
            "heatDays": 0,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.98
          },
          {
            "asOf": "2026-06-30",
            "observedThrough": "2026-06-30",
            "rainfallLast7DaysMm": 11.4,
            "rainfallLast30DaysMm": 242.1,
            "avgTempLast30DaysF": 72.8,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1069.0,
            "heatDays": 0,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.98
          },
          {
            "asOf": "2026-07-15",
            "observedThrough": "2026-07-15",
            "rainfallLast7DaysMm": 8.1,
            "rainfallLast30DaysMm": 133.9,
            "avgTempLast30DaysF": 75.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1405.0,
            "heatDays": 3,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.95
          },
          {
            "asOf": "2026-07-22",
            "observedThrough": "2026-07-22",
            "rainfallLast7DaysMm": 44.7,
            "rainfallLast30DaysMm": 75.9,
            "avgTempLast30DaysF": 77.6,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1562.0,
            "heatDays": 3,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.94
          },
          {
            "asOf": "2026-07-30",
            "observedThrough": "2026-07-30",
            "rainfallLast7DaysMm": 0.8,
            "rainfallLast30DaysMm": 65.3,
            "avgTempLast30DaysF": 77.1,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1726.0,
            "heatDays": 3,
            "longestDrySpellDays": 11,
            "dataCompleteness": 0.95
          },
          {
            "asOf": "2026-08-15",
            "observedThrough": "2026-08-15",
            "rainfallLast7DaysMm": 103.4,
            "rainfallLast30DaysMm": 231.4,
            "avgTempLast30DaysF": 74.9,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2108.0,
            "heatDays": 3,
            "longestDrySpellDays": 12,
            "dataCompleteness": 0.94
          },
          {
            "asOf": "2026-09-01",
            "observedThrough": "2026-08-31",
            "rainfallLast7DaysMm": 10.7,
            "rainfallLast30DaysMm": 148.6,
            "avgTempLast30DaysF": 75.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2488.0,
            "heatDays": 3,
            "longestDrySpellDays": 12,
            "dataCompleteness": 0.94
          }
        ],
        "source": "NOAA NCEI GHCN-Daily",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "yieldHistory": {
      "status": "ok",
      "data": {
        "county": {
          "name": "Tippecanoe County",
          "stateCode": "IN",
          "stateName": "Indiana",
          "fips": "18157"
        },
        "years": [
          {
            "year": 2017,
            "yield": 180.3
          },
          {
            "year": 2018,
            "yield": 201.1
          },
          {
            "year": 2019,
            "yield": 180.4
          },
          {
            "year": 2020,
            "yield": 207.1
          },
          {
            "year": 2021,
            "yield": 207.2
          },
          {
            "year": 2022,
            "yield": 188.6
          },
          {
            "year": 2023,
            "yield": 222.4
          },
          {
            "year": 2024,
            "yield": 220.0
          },
          {
            "year": 2025,
            "yield": 233.4
          }
        ],
        "fiveYearAverage": 214.3,
        "unit": "bu/ac",
        "source": "USDA NASS Quick Stats",
        "retrievedAt": "2026-09-24T05:41:02+00:00"
      },
      "message": null
    }
  },
  "purdue-221": {
    "latitude": 40.4612,
    "longitude": -86.9912,
    "county": {
      "name": "Tippecanoe County",
      "stateCode": "IN",
      "stateName": "Indiana",
      "fips": "18157"
    },
    "soil": {
      "status": "ok",
      "data": {
        "mapUnitKey": "164150",
        "mapUnitName": "Miami silt loam, well drained, 12 to 18 percent slopes, eroded",
        "series": "Miami",
        "componentPercent": 92.0,
        "taxonomicClass": "Fine-loamy, mixed, active, mesic Typic Hapludalfs",
        "texture": "Silt loam",
        "drainage": "Well drained",
        "hydrologicGroup": "C",
        "availableWaterCapacity": 0.122,
        "availableWaterStorageCm": 12.2,
        "availableWaterClass": "Moderate",
        "organicMatter": 2.0,
        "ph": 6.5,
        "rootZoneDepthCm": 71.0,
        "slopePercent": 15.0,
        "source": "USDA NRCS SSURGO",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "weather": {
      "status": "ok",
      "data": {
        "station": {
          "id": "USC00129430",
          "name": "West Lafayette 6 NW, IN",
          "latitude": 40.475,
          "longitude": -86.9919,
          "distanceKm": 1.5
        },
        "summaries": [
          {
            "asOf": "2026-05-30",
            "observedThrough": "2026-05-30",
            "rainfallLast7DaysMm": 3.8,
            "rainfallLast30DaysMm": 64.5,
            "avgTempLast30DaysF": 61.6,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 388.0,
            "heatDays": 0,
            "longestDrySpellDays": 3,
            "dataCompleteness": 0.97
          },
          {
            "asOf": "2026-06-15",
            "observedThrough": "2026-06-15",
            "rainfallLast7DaysMm": 85.6,
            "rainfallLast30DaysMm": 152.1,
            "avgTempLast30DaysF": 72.1,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 760.0,
            "heatDays": 0,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.98
          },
          {
            "asOf": "2026-06-30",
            "observedThrough": "2026-06-30",
            "rainfallLast7DaysMm": 11.4,
            "rainfallLast30DaysMm": 242.1,
            "avgTempLast30DaysF": 72.8,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1069.0,
            "heatDays": 0,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.98
          },
          {
            "asOf": "2026-07-15",
            "observedThrough": "2026-07-15",
            "rainfallLast7DaysMm": 8.1,
            "rainfallLast30DaysMm": 133.9,
            "avgTempLast30DaysF": 75.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1405.0,
            "heatDays": 3,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.95
          },
          {
            "asOf": "2026-07-22",
            "observedThrough": "2026-07-22",
            "rainfallLast7DaysMm": 44.7,
            "rainfallLast30DaysMm": 75.9,
            "avgTempLast30DaysF": 77.6,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1562.0,
            "heatDays": 3,
            "longestDrySpellDays": 8,
            "dataCompleteness": 0.94
          },
          {
            "asOf": "2026-07-30",
            "observedThrough": "2026-07-30",
            "rainfallLast7DaysMm": 0.8,
            "rainfallLast30DaysMm": 65.3,
            "avgTempLast30DaysF": 77.1,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1726.0,
            "heatDays": 3,
            "longestDrySpellDays": 11,
            "dataCompleteness": 0.95
          },
          {
            "asOf": "2026-08-15",
            "observedThrough": "2026-08-15",
            "rainfallLast7DaysMm": 103.4,
            "rainfallLast30DaysMm": 231.4,
            "avgTempLast30DaysF": 74.9,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2108.0,
            "heatDays": 3,
            "longestDrySpellDays": 12,
            "dataCompleteness": 0.94
          },
          {
            "asOf": "2026-09-01",
            "observedThrough": "2026-08-31",
            "rainfallLast7DaysMm": 10.7,
            "rainfallLast30DaysMm": 148.6,
            "avgTempLast30DaysF": 75.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2488.0,
            "heatDays": 3,
            "longestDrySpellDays": 12,
            "dataCompleteness": 0.94
          }
        ],
        "source": "NOAA NCEI GHCN-Daily",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "yieldHistory": {
      "status": "ok",
      "data": {
        "county": {
          "name": "Tippecanoe County",
          "stateCode": "IN",
          "stateName": "Indiana",
          "fips": "18157"
        },
        "years": [
          {
            "year": 2017,
            "yield": 180.3
          },
          {
            "year": 2018,
            "yield": 201.1
          },
          {
            "year": 2019,
            "yield": 180.4
          },
          {
            "year": 2020,
            "yield": 207.1
          },
          {
            "year": 2021,
            "yield": 207.2
          },
          {
            "year": 2022,
            "yield": 188.6
          },
          {
            "year": 2023,
            "yield": 222.4
          },
          {
            "year": 2024,
            "yield": 220.0
          },
          {
            "year": 2025,
            "yield": 233.4
          }
        ],
        "fiveYearAverage": 214.3,
        "unit": "bu/ac",
        "source": "USDA NASS Quick Stats",
        "retrievedAt": "2026-09-24T05:41:02+00:00"
      },
      "message": null
    }
  },
  "illinois-18": {
    "latitude": 40.185,
    "longitude": -88.339,
    "county": {
      "name": "Champaign County",
      "stateCode": "IL",
      "stateName": "Illinois",
      "fips": "17019"
    },
    "soil": {
      "status": "ok",
      "data": {
        "mapUnitKey": "242963",
        "mapUnitName": "Drummer silty clay loam, 0 to 2 percent slopes",
        "series": "Drummer",
        "componentPercent": 94.0,
        "taxonomicClass": "Fine-silty, mixed, superactive, mesic Typic Endoaquolls",
        "texture": "Silty clay loam",
        "drainage": "Poorly drained",
        "hydrologicGroup": "B/D",
        "availableWaterCapacity": 0.174,
        "availableWaterStorageCm": 17.4,
        "availableWaterClass": "High",
        "organicMatter": 5.5,
        "ph": 6.7,
        "rootZoneDepthCm": 152.0,
        "slopePercent": 0.5,
        "source": "USDA NRCS SSURGO",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "weather": {
      "status": "ok",
      "data": {
        "station": {
          "id": "USC00118740",
          "name": "Champaign 3 S, IL",
          "latitude": 40.08408,
          "longitude": -88.24039,
          "distanceKm": 14.0
        },
        "summaries": [
          {
            "asOf": "2026-05-30",
            "observedThrough": "2026-05-30",
            "rainfallLast7DaysMm": 5.8,
            "rainfallLast30DaysMm": 52.8,
            "avgTempLast30DaysF": 62.0,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 400.0,
            "heatDays": 0,
            "longestDrySpellDays": 7,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-07-22",
            "observedThrough": "2026-07-22",
            "rainfallLast7DaysMm": 7.9,
            "rainfallLast30DaysMm": 63.5,
            "avgTempLast30DaysF": 77.4,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1672.0,
            "heatDays": 0,
            "longestDrySpellDays": 11,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-09-01",
            "observedThrough": "2026-09-01",
            "rainfallLast7DaysMm": 0.5,
            "rainfallLast30DaysMm": 223.5,
            "avgTempLast30DaysF": 74.8,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2596.0,
            "heatDays": 0,
            "longestDrySpellDays": 11,
            "dataCompleteness": 0.98
          }
        ],
        "source": "NOAA NCEI GHCN-Daily",
        "retrievedAt": "2026-09-24T05:16:46+00:00"
      },
      "message": null
    },
    "yieldHistory": {
      "status": "ok",
      "data": {
        "county": {
          "name": "Champaign County",
          "stateCode": "IL",
          "stateName": "Illinois",
          "fips": "17019"
        },
        "years": [
          {
            "year": 2016,
            "yield": 210.2
          },
          {
            "year": 2017,
            "yield": 206.8
          },
          {
            "year": 2018,
            "yield": 221.3
          },
          {
            "year": 2019,
            "yield": 180.8
          },
          {
            "year": 2020,
            "yield": 192.7
          },
          {
            "year": 2021,
            "yield": 222.4
          },
          {
            "year": 2022,
            "yield": 219.1
          },
          {
            "year": 2023,
            "yield": 218.2
          }
        ],
        "fiveYearAverage": 206.6,
        "unit": "bu/ac",
        "source": "USDA NASS Quick Stats",
        "retrievedAt": "2026-09-24T05:41:04+00:00"
      },
      "message": null
    }
  },
  "nebraska-42": {
    "latitude": 40.98117,
    "longitude": -98.66309,
    "county": {
      "name": "Hall County",
      "stateCode": "NE",
      "stateName": "Nebraska",
      "fips": "31079"
    },
    "soil": {
      "status": "ok",
      "data": {
        "mapUnitKey": "1700146",
        "mapUnitName": "Holdrege silt loam, 1 to 3 percent slopes, overblown",
        "series": "Holdrege",
        "componentPercent": 95.0,
        "taxonomicClass": "Fine-silty, mixed, superactive, mesic Typic Argiustolls",
        "texture": "Silt loam",
        "drainage": "Well drained",
        "hydrologicGroup": "C",
        "availableWaterCapacity": 0.213,
        "availableWaterStorageCm": 21.3,
        "availableWaterClass": "High",
        "organicMatter": 2.0,
        "ph": 6.2,
        "rootZoneDepthCm": 200.0,
        "slopePercent": 2.0,
        "source": "USDA NRCS SSURGO",
        "retrievedAt": "2026-09-24T05:16:47+00:00"
      },
      "message": null
    },
    "weather": {
      "status": "ok",
      "data": {
        "station": {
          "id": "USC00257040",
          "name": "Ravenna, NE",
          "latitude": 41.0319,
          "longitude": -98.9213,
          "distanceKm": 22.4
        },
        "summaries": [
          {
            "asOf": "2026-05-30",
            "observedThrough": "2026-05-30",
            "rainfallLast7DaysMm": 27.7,
            "rainfallLast30DaysMm": 77.5,
            "avgTempLast30DaysF": 59.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 387.0,
            "heatDays": 0,
            "longestDrySpellDays": 10,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-07-22",
            "observedThrough": "2026-07-22",
            "rainfallLast7DaysMm": 0.5,
            "rainfallLast30DaysMm": 49.8,
            "avgTempLast30DaysF": 75.7,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1552.0,
            "heatDays": 3,
            "longestDrySpellDays": 12,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-09-01",
            "observedThrough": "2026-08-31",
            "rainfallLast7DaysMm": 6.3,
            "rainfallLast30DaysMm": 55.6,
            "avgTempLast30DaysF": 74.3,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2264.0,
            "heatDays": 6,
            "longestDrySpellDays": 12,
            "dataCompleteness": 0.91
          }
        ],
        "source": "NOAA NCEI GHCN-Daily",
        "retrievedAt": "2026-09-24T05:16:47+00:00"
      },
      "message": null
    },
    "yieldHistory": {
      "status": "ok",
      "data": {
        "county": {
          "name": "Hall County",
          "stateCode": "NE",
          "stateName": "Nebraska",
          "fips": "31079"
        },
        "years": [
          {
            "year": 2016,
            "yield": 186.4
          },
          {
            "year": 2017,
            "yield": 199.8
          },
          {
            "year": 2018,
            "yield": 217.5
          },
          {
            "year": 2019,
            "yield": 180.4
          },
          {
            "year": 2020,
            "yield": 201.8
          },
          {
            "year": 2022,
            "yield": 188.2
          },
          {
            "year": 2023,
            "yield": 214.9
          },
          {
            "year": 2024,
            "yield": 214.7
          },
          {
            "year": 2025,
            "yield": 210.4
          }
        ],
        "fiveYearAverage": 206.0,
        "unit": "bu/ac",
        "source": "USDA NASS Quick Stats",
        "retrievedAt": "2026-09-24T05:41:06+00:00"
      },
      "message": null
    }
  },
  "iowa-07": {
    "latitude": 42.00786,
    "longitude": -93.5588,
    "county": {
      "name": "Story County",
      "stateCode": "IA",
      "stateName": "Iowa",
      "fips": "19169"
    },
    "soil": {
      "status": "ok",
      "data": {
        "mapUnitKey": "2800480",
        "mapUnitName": "Nicollet loam, 1 to 3 percent slopes",
        "series": "Nicollet",
        "componentPercent": 85.0,
        "taxonomicClass": "Fine-loamy, mixed, superactive, mesic Aquic Hapludolls",
        "texture": "Loam",
        "drainage": "Somewhat poorly drained",
        "hydrologicGroup": "B/D",
        "availableWaterCapacity": 0.191,
        "availableWaterStorageCm": 19.1,
        "availableWaterClass": "High",
        "organicMatter": 6.0,
        "ph": 6.2,
        "rootZoneDepthCm": 200.0,
        "slopePercent": 2.0,
        "source": "USDA NRCS SSURGO",
        "retrievedAt": "2026-09-24T05:16:47+00:00"
      },
      "message": null
    },
    "weather": {
      "status": "ok",
      "data": {
        "station": {
          "id": "USW00094989",
          "name": "Ames Municipal Airport, IA",
          "latitude": 41.99045,
          "longitude": -93.61852,
          "distanceKm": 5.3
        },
        "summaries": [
          {
            "asOf": "2026-05-30",
            "observedThrough": "2026-05-30",
            "rainfallLast7DaysMm": 1.3,
            "rainfallLast30DaysMm": 78.7,
            "avgTempLast30DaysF": 62.1,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 431.0,
            "heatDays": 0,
            "longestDrySpellDays": 14,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-07-22",
            "observedThrough": "2026-07-22",
            "rainfallLast7DaysMm": 96.5,
            "rainfallLast30DaysMm": 312.7,
            "avgTempLast30DaysF": 76.2,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 1634.0,
            "heatDays": 0,
            "longestDrySpellDays": 14,
            "dataCompleteness": 1.0
          },
          {
            "asOf": "2026-09-01",
            "observedThrough": "2026-09-01",
            "rainfallLast7DaysMm": 9.1,
            "rainfallLast30DaysMm": 129.3,
            "avgTempLast30DaysF": 73.2,
            "seasonStart": "2026-05-01",
            "gddSinceSeasonStart": 2584.0,
            "heatDays": 2,
            "longestDrySpellDays": 14,
            "dataCompleteness": 1.0
          }
        ],
        "source": "NOAA NCEI GHCN-Daily",
        "retrievedAt": "2026-09-24T05:16:47+00:00"
      },
      "message": null
    },
    "yieldHistory": {
      "status": "ok",
      "data": {
        "county": {
          "name": "Story County",
          "stateCode": "IA",
          "stateName": "Iowa",
          "fips": "19169"
        },
        "years": [
          {
            "year": 2016,
            "yield": 211.9
          },
          {
            "year": 2017,
            "yield": 200.3
          },
          {
            "year": 2018,
            "yield": 192.3
          },
          {
            "year": 2019,
            "yield": 189.3
          },
          {
            "year": 2020,
            "yield": 148.4
          },
          {
            "year": 2021,
            "yield": 201.2
          },
          {
            "year": 2022,
            "yield": 207.1
          },
          {
            "year": 2023,
            "yield": 211.4
          },
          {
            "year": 2024,
            "yield": 215.5
          },
          {
            "year": 2025,
            "yield": 204.0
          }
        ],
        "fiveYearAverage": 207.8,
        "unit": "bu/ac",
        "source": "USDA NASS Quick Stats",
        "retrievedAt": "2026-09-24T05:41:10+00:00"
      },
      "message": null
    }
  }
};
