/**
 * The five SyDAg26 trial sites, for the demo build (which has no API).
 * Generated by backend/scripts/export_trial_sites.py; do not edit by hand.
 * API mode reads the same list from GET /api/sites, with live availability added.
 */

import type { TrialSite } from '../types/sites';

export const TRIAL_SITES: TrialSite[] = [
  {
    "id": "Ames",
    "name": "Ames",
    "state": "IA",
    "stateName": "Iowa",
    "latitude": 42.014713,
    "longitude": -93.732245,
    "coordinateSource": "plot_centroids",
    "crop": "Maize",
    "irrigated": false,
    "seasons": [
      {
        "year": 2022,
        "plantingDates": [
          "2022-05-22",
          "2022-05-23"
        ],
        "plots": 536,
        "plotsWithYield": 487,
        "hybrids": 84,
        "satellite": {
          "acquisitions": 6,
          "acquisitionDates": [
            "2022-07-15",
            "2022-07-23",
            "2022-08-10",
            "2022-08-31",
            "2022-09-11",
            "2022-09-24"
          ],
          "plotImages": 662,
          "plotsImaged": 256
        },
        "uav": {
          "acquisitions": 3,
          "acquisitionDates": [
            "2022-07-12",
            "2022-07-26",
            "2022-08-10"
          ],
          "plotImages": 412,
          "plotsImaged": 166
        }
      }
    ]
  },
  {
    "id": "Crawfordsville",
    "name": "Crawfordsville",
    "state": "IA",
    "stateName": "Iowa",
    "latitude": 41.198935,
    "longitude": -91.486866,
    "coordinateSource": "plot_centroids",
    "crop": "Maize",
    "irrigated": false,
    "seasons": [
      {
        "year": 2022,
        "plantingDates": [
          "2022-05-11"
        ],
        "plots": 522,
        "plotsWithYield": 488,
        "hybrids": 84,
        "satellite": {
          "acquisitions": 6,
          "acquisitionDates": [
            "2022-07-10",
            "2022-07-20",
            "2022-08-02",
            "2022-09-13",
            "2022-10-01",
            "2022-10-09"
          ],
          "plotImages": 500,
          "plotsImaged": 332
        },
        "uav": {
          "acquisitions": 3,
          "acquisitionDates": [
            "2022-07-12",
            "2022-07-26",
            "2022-08-11"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        }
      }
    ]
  },
  {
    "id": "Lincoln",
    "name": "Lincoln",
    "state": "NE",
    "stateName": "Nebraska",
    "latitude": 40.8522,
    "longitude": -96.615341,
    "coordinateSource": "plot_centroids",
    "crop": "Maize",
    "irrigated": false,
    "seasons": [
      {
        "year": 2022,
        "plantingDates": [
          "2022-05-22"
        ],
        "plots": 532,
        "plotsWithYield": 504,
        "hybrids": 84,
        "satellite": {
          "acquisitions": 6,
          "acquisitionDates": [
            "2022-07-18",
            "2022-08-06",
            "2022-09-03",
            "2022-09-11",
            "2022-09-19",
            "2022-09-27"
          ],
          "plotImages": 798,
          "plotsImaged": 438
        },
        "uav": {
          "acquisitions": 3,
          "acquisitionDates": [
            "2022-07-13",
            "2022-07-28",
            "2022-08-04"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        }
      }
    ]
  },
  {
    "id": "MOValley",
    "name": "Missouri Valley",
    "state": "IA",
    "stateName": "Iowa",
    "latitude": 41.671,
    "longitude": -95.942,
    "coordinateSource": "practice_site_reference",
    "crop": "Maize",
    "irrigated": false,
    "seasons": [
      {
        "year": 2022,
        "plantingDates": [
          "2022-04-29"
        ],
        "plots": 176,
        "plotsWithYield": 163,
        "hybrids": 84,
        "satellite": {
          "acquisitions": 6,
          "acquisitionDates": [
            "2022-07-13",
            "2022-07-21",
            "2022-08-08",
            "2022-09-03",
            "2022-09-11",
            "2022-09-19"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        },
        "uav": {
          "acquisitions": 3,
          "acquisitionDates": [
            "2022-07-13",
            "2022-07-27",
            "2022-08-10"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        }
      }
    ]
  },
  {
    "id": "Scottsbluff",
    "name": "Scottsbluff",
    "state": "NE",
    "stateName": "Nebraska",
    "latitude": 41.95,
    "longitude": -103.703,
    "coordinateSource": "practice_site_reference",
    "crop": "Maize",
    "irrigated": true,
    "seasons": [
      {
        "year": 2022,
        "plantingDates": [
          "2022-05-19"
        ],
        "plots": 525,
        "plotsWithYield": 489,
        "hybrids": 84,
        "satellite": {
          "acquisitions": 6,
          "acquisitionDates": [
            "2022-07-04",
            "2022-07-17",
            "2022-08-07",
            "2022-08-18",
            "2022-09-09",
            "2022-09-24"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        },
        "uav": {
          "acquisitions": 3,
          "acquisitionDates": [
            "2022-07-08",
            "2022-07-22",
            "2022-08-12"
          ],
          "plotImages": 0,
          "plotsImaged": 0
        }
      }
    ]
  }
];
