"""Command implementations for `python -m soilsignal_ml.weather_outlook`."""

import json
from datetime import date, timedelta
from pathlib import Path
from typing import Any

import pandas as pd

from soilsignal_ml import BACKEND_ROOT
from soilsignal_ml.weather_outlook.history import (
    PUBLISH_DIR,
    REPORT_DIR,
    SiteHistory,
    build_long,
    build_supplied,
    fetch_ghcn,
    load_config,
    load_supplied,
    publish,
)

SUPPLIED_LABEL = "Challenge weather file, 2018-2023 (exploratory)"
LONG_LABEL = "Long-record library, NOAA GHCN-Daily"


def run_history(which: str, refresh: bool, end: date | None) -> int:
    cfg = load_config()
    end = end or (date.today() - timedelta(days=2))
    built: dict[str, list[SiteHistory]] = {}
    if which in ("supplied", "all"):
        built["supplied"] = build_supplied(cfg)
        publish("supplied", SUPPLIED_LABEL, built["supplied"], cfg)
    if which in ("long", "all"):
        built["long"] = build_long(cfg, end, refresh=refresh)
        publish("long", LONG_LABEL, built["long"], cfg)
    for name, sites in built.items():
        for h in sites:
            kept = int(h.qc["included"].sum())
            print(
                f"{name:9s} {h.site:15s} {h.station['id']:12s} {kept:3d} seasons kept, "
                f"{int((~h.qc['included']).sum())} left out"
            )
    write_qc_report(cfg, built, end, refresh)
    print(f"published to {PUBLISH_DIR}; QC report {REPORT_DIR / 'data_qc.md'}")
    return 0


def _supplied_vs_official(cfg: dict[str, Any], end: date, refresh: bool) -> pd.DataFrame:
    """The challenge file against NOAA's official daily record for the same airport
    stations, per season (April-October): mean temperature differences, rain ratio."""
    daily, _ = load_supplied(cfg)
    rows = []
    for site, spec in cfg["sites"].items():
        if not spec["long"]["same_as_supplied"]:
            continue
        start = date(cfg["seasons"]["long_first_season"] - 1, 10, 1)
        official = fetch_ghcn(spec["long"]["station"], start, end, refresh=refresh)
        ours = daily[daily["site"] == site]
        merged = ours.merge(official, on="date", suffixes=("_file", "_noaa"))
        merged = merged[merged["date"].dt.month.between(4, 10)]
        for year, g in merged.groupby(merged["date"].dt.year):
            rows.append(
                {
                    "site": site,
                    "season": int(year),
                    "tmax_file_minus_noaa_c": round(
                        float((g["tmax_c_file"] - g["tmax_c_noaa"]).mean()), 2
                    ),
                    "tmin_file_minus_noaa_c": round(
                        float((g["tmin_c_file"] - g["tmin_c_noaa"]).mean()), 2
                    ),
                    "heat_days_file": int((g["tmax_c_file"] >= 35).sum()),
                    "heat_days_noaa": int((g["tmax_c_noaa"] >= 35).sum()),
                    "precip_ratio_file_to_noaa": round(
                        float(g["precip_mm_file"].sum() / g["precip_mm_noaa"].sum()), 3
                    ),
                }
            )
    return pd.DataFrame(rows)


def write_qc_report(
    cfg: dict[str, Any], built: dict[str, list[SiteHistory]], end: date, refresh: bool
) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    daily, meta = load_supplied(cfg)
    lines = [
        "# Weather data QC",
        "",
        "Generated by `python -m soilsignal_ml.weather_outlook history`. Method and "
        "decisions: `ml/research/weather_outlook.md`.",
        "",
    ]
    lines += [
        "## 1. The supplied challenge file",
        "",
        f"`{cfg['supplied']['file']}`: {len(daily):,} rows, "
        f"{daily['site'].nunique()} sites, {daily['date'].min().date()} to "
        f"{daily['date'].max().date()}, one station per site, no duplicate site-days "
        f"({int(daily.duplicated(['site', 'date']).sum())} found).",
        "",
    ]
    raw = pd.read_csv(
        Path(__file__).resolve().parents[2] / cfg["supplied"]["file"], low_memory=False
    )
    columns = [
        "tmax_c",
        "tmin_c",
        "precip_mm",
        "avg_rh",
        "avg_wind_speed_mps",
        "srad_mj",
        "et_mm",
        "soil_vwc_12in",
    ]
    cov = raw.groupby("site_name")[columns].apply(lambda g: g.notna().mean()).T
    lines += [
        "Share of days with a value, by column (normalized columns only; the file also "
        "carries each source's raw columns, which are not used):",
        "",
        "| column | " + " | ".join(cov.columns) + " |",
        "|---|" + "---|" * len(cov.columns),
    ]
    for column, row in cov.iterrows():
        lines.append(f"| `{column}` | " + " | ".join(f"{v:.0%}" for v in row) + " |")
    lines += [
        "",
        "Solar radiation, ET and soil moisture exist only for Crawfordsville (ISU Soil "
        "Moisture Network), so the five-site outlook uses temperature and precipitation "
        "only. Humidity and wind are nearly complete but are not in NOAA's long records "
        "and are not needed by the SoilSignal weather features.",
        "",
    ]
    growing = raw[pd.to_datetime(raw["date"]).dt.month.between(4, 10)]
    miss = growing.groupby("site_name")[["tmax_c", "tmin_c", "precip_mm"]].apply(
        lambda g: g.isna().sum()
    )
    lines += [
        "Missing days in April-October 2018-2023: "
        + "; ".join(f"{s}: {int(r.sum())}" for s, r in miss.iterrows())
        + ".",
        "",
    ]
    off = _supplied_vs_official(cfg, end, refresh)
    if not off.empty:
        off.to_csv(REPORT_DIR / "supplied_vs_noaa.csv", index=False)
        lines += [
            "### The file against NOAA's official record for the same stations",
            "",
            "The file is IEM's *computed* daily summary. Against NOAA GHCN-Daily for the "
            "same airport (April-October means; heat days = tmax >= 35 C / 95 F):",
            "",
            "| site | season | tmax file - NOAA (C) | tmin file - NOAA (C) | heat days file / NOAA | rain file / NOAA |",
            "|---|---|---|---|---|---|",
        ]
        for _, r in off.iterrows():
            lines.append(
                f"| {r['site']} | {r['season']} | {r['tmax_file_minus_noaa_c']:+.2f} | "
                f"{r['tmin_file_minus_noaa_c']:+.2f} | {r['heat_days_file']} / {r['heat_days_noaa']} | "
                f"{r['precip_ratio_file_to_noaa']:.2f} |"
            )
        lines += [
            "",
            "From 2020 the file's daily maxima run about 0.4 C below the official "
            "maxima and its minima about 0.5 C above (2018-2019 match), consistent with "
            "extremes computed from hourly reports rather than the official 24-hour "
            "max/min. The file under-counts 95 F days in those years. The long library "
            "therefore uses NOAA's official record; the supplied library is kept exactly "
            "as delivered.",
            "",
        ]
    for name, sites in built.items():
        lines += [
            f"## Library `{name}`",
            "",
            "| site | station | seasons kept | left out |",
            "|---|---|---|---|",
        ]
        for h in sites:
            kept = [int(y) for y in h.qc.index[h.qc["included"]]]
            span = f"{len(kept)} ({min(kept)}-{max(kept)})" if kept else "0"
            gone = "; ".join(f"{y}: {r}" for y, r in h.qc.loc[~h.qc["included"], "reason"].items())
            lines.append(
                f"| {h.site} | {h.station['id']} {h.station['name']} | {span} | {gone or '-'} |"
            )
        lines.append("")
        for h in sites:
            overlap = h.station.get("overlap")
            if overlap:
                adj = overlap["monthly_temperature_adjustment_c"]
                lines += [
                    f"### {h.site}: proxy station {h.station['id']} against {overlap['reference_station']}",
                    "",
                    f"Overlap {overlap['first']} to {overlap['last']} ({overlap['days']} days). "
                    f"April-October daily correlation after aligning the 07:00 observation day: "
                    + ", ".join(f"{k} {v}" for k, v in overlap["daily_correlation"].items())
                    + f". Mean difference proxy - site: tmax {overlap['mean_difference_c']['tmax_c']:+.2f} C, "
                    f"tmin {overlap['mean_difference_c']['tmin_c']:+.2f} C. Season rain ratio "
                    f"{overlap['season_precip_ratio']:.2f}, season-total correlation "
                    f"{overlap['season_precip_correlation']:.2f}.",
                    "",
                    "Monthly adjustment added to exported trajectories (site - proxy, C): "
                    + ", ".join(
                        f"{m}: {adj['tmax_c'][m]:+.1f}/{adj['tmin_c'][m]:+.1f}"
                        for m in sorted(adj["tmax_c"], key=int)
                    )
                    + " (tmax/tmin).",
                    "",
                ]
    (REPORT_DIR / "data_qc.md").write_text("\n".join(lines) + "\n")


def _library(name: str):
    from app.weather_outlook.history import WeatherLibrary

    return WeatherLibrary(PUBLISH_DIR / name)


def run_outlook(
    library: str, site: str, as_of: date, horizon, planting, parquet: Path | None
) -> dict:
    from app.weather_outlook.contract import to_contract, trajectories_frame
    from app.weather_outlook.scenarios import WeatherOutlook

    outlook = WeatherOutlook(_library(library)).generate(site, as_of, horizon, planting=planting)
    if parquet:
        parquet.parent.mkdir(parents=True, exist_ok=True)
        trajectories_frame(outlook).to_parquet(parquet, index=False)
    return to_contract(outlook)


def run_yield(
    library: str, bundle_path: Path | None, plot: str | None, model: str | None, as_of: date
) -> int:
    """Layer 2 on the practice data: every historical trajectory through an exported model."""
    from app.forecast.bundle import Bundle
    from app.model.artifact import FeatureValidationError, ModelRegistry
    from app.weather_outlook.contract import to_contract
    from app.weather_outlook.coupling import artifact_predictor
    from app.weather_outlook.scenarios import WeatherOutlook, couple_yield

    bundle = Bundle.load(bundle_path or BACKEND_ROOT / "data" / "practice" / "shrestha2024.json")
    plot_id = plot or next(iter(bundle.plots))
    inputs = bundle.inputs(plot_id)
    registry = ModelRegistry.load(BACKEND_ROOT / "artifacts")
    artifacts = [registry.get(model)] if model else registry.artifacts
    site = bundle.site["name"] if isinstance(bundle.site, dict) else bundle.site.name
    engine = WeatherOutlook(_library(library))
    outlook = engine.generate(
        site, as_of, "season", planting=inputs.planting_date, current_weather=inputs.weather
    )
    results = {}
    for artifact in artifacts:
        feature_date = date(as_of.year, *(int(p) for p in artifact.metadata.as_of.split("-")))
        if feature_date < as_of:
            continue
        predict = artifact_predictor(artifact, inputs, as_of, feature_date)
        try:
            coupled = couple_yield(outlook, predict)
        except FeatureValidationError as err:
            results[artifact.metadata.model_id] = {
                "featureDate": feature_date.isoformat(),
                "error": f"cannot score a plot frozen at {as_of}: {err}"[:400],
            }
            continue
        doc = to_contract(coupled.outlook, coupled)
        results[artifact.metadata.model_id] = {
            "featureDate": feature_date.isoformat(),
            "weatherFeaturesUsed": [f for f in artifact.schema.names if _is_weather(f)],
            "categoryBasis": doc["categoryBasis"],
            "probabilities": doc["probabilities"],
            "yield": doc["yield"],
        }
    print(
        json.dumps(
            {
                "plot": plot_id,
                "site": site,
                "asOfDate": as_of.isoformat(),
                "library": library,
                "models": results,
            },
            indent=2,
        )
    )
    return 0


def _is_weather(feature: str) -> bool:
    from app.features.catalog import CATALOG

    entry = CATALOG.get(feature)
    return bool(entry) and getattr(entry, "category", None) == "Weather"
