import { useEffect, useMemo, useState, type KeyboardEvent } from 'react';
import { AnimatePresence, motion, useReducedMotion } from 'motion/react';
import { ArrowRight, Check, Minus } from 'lucide-react';
import type { TrialSite } from '../../types/sites';
import { getTrialSites, hasForecasts, isMappable } from '../../services/sites';
import { formatNumber } from '../../utils/formatters';
import { EASE_OUT } from '../../utils/motion';
import { PALETTE as C } from '../../utils/palette';
import { Link } from '../../utils/router';
import { projectLonLat, US_MAP_SIZE, US_STATES } from './usMap';

const LABEL_FONT = 15;
const CHAR_W = LABEL_FONT * 0.56;

interface Box {
  x0: number;
  y0: number;
  x1: number;
  y1: number;
}

interface Marker {
  site: TrialSite;
  x: number;
  y: number;
  label: { x: number; y: number; anchor: 'start' | 'middle' | 'end' };
  /** A short line from the marker to a label placed farther out. */
  leader: { x1: number; y1: number; x2: number; y2: number } | null;
}

const area = (a: Box, b: Box) =>
  Math.max(0, Math.min(a.x1, b.x1) - Math.max(a.x0, b.x0)) * Math.max(0, Math.min(a.y1, b.y1) - Math.max(a.y0, b.y0));

/**
 * Places each label beside its marker where it overlaps no other marker or label: next
 * to it if possible, else a step farther out with a leader line, else wherever it
 * overlaps least.
 */
function placeLabels(sites: TrialSite[]): Marker[] {
  const points = sites.map((site) => {
    const [x, y] = projectLonLat(site.longitude, site.latitude);
    return { site, x, y };
  });
  const taken: Box[] = points.map((p) => ({ x0: p.x - 9, y0: p.y - 9, x1: p.x + 9, y1: p.y + 9 }));
  // West to east, so the crowded eastern cluster is placed around the settled western labels.
  return [...points]
    .sort((a, b) => a.x - b.x)
    .map((p) => {
      const w = p.site.name.length * CHAR_W;
      const candidates = [0, 18].flatMap((far) => {
        const g = 12 + far;
        const leader = (x2: number, y2: number) =>
          far ? { x1: p.x + Math.sign(x2 - p.x) * 7, y1: p.y + Math.sign(y2 - p.y) * 7, x2, y2 } : null;
        return [
          {
            label: { x: p.x, y: p.y - g - 4, anchor: 'middle' as const },
            box: { x0: p.x - w / 2, y0: p.y - g - 18, x1: p.x + w / 2, y1: p.y - g },
            leader: leader(p.x, p.y - g),
          },
          {
            label: { x: p.x, y: p.y + g + 14, anchor: 'middle' as const },
            box: { x0: p.x - w / 2, y0: p.y + g, x1: p.x + w / 2, y1: p.y + g + 18 },
            leader: leader(p.x, p.y + g),
          },
          {
            label: { x: p.x + g + 2, y: p.y + 5, anchor: 'start' as const },
            box: { x0: p.x + g, y0: p.y - 9, x1: p.x + g + 2 + w, y1: p.y + 9 },
            leader: leader(p.x + g, p.y),
          },
          {
            label: { x: p.x - g - 2, y: p.y + 5, anchor: 'end' as const },
            box: { x0: p.x - g - 2 - w, y0: p.y - 9, x1: p.x - g, y1: p.y + 9 },
            leader: leader(p.x - g, p.y),
          },
        ];
      });
      const cost = (b: Box) => taken.reduce((sum, o) => sum + area(b, o), 0);
      const chosen = candidates.find((c) => cost(c.box) === 0) ?? [...candidates].sort((a, b) => cost(a.box) - cost(b.box))[0];
      taken.push(chosen.box);
      return { ...p, label: chosen.label, leader: chosen.leader };
    });
}

/**
 * The trial locations on a quiet map of the contiguous U.S. (outlines generated by
 * scripts/build-us-map.mjs; no map library). The sites and every fact in the panel
 * come from GET /api/sites; nothing about model accuracy is shown here.
 */
export function TrialSiteMap() {
  const reduce = useReducedMotion();
  const [sites, setSites] = useState<TrialSite[] | null>(null);
  const [failed, setFailed] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [hoverId, setHoverId] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    getTrialSites()
      .then((list) => {
        if (!active) return;
        const mapped = list.filter(isMappable);
        setSites(mapped);
        setSelectedId((current) => current ?? (mapped.find(hasForecasts) ?? mapped[0])?.id ?? null);
      })
      .catch(() => active && setFailed(true));
    return () => {
      active = false;
    };
  }, []);

  const markers = useMemo(() => (sites ? placeLabels(sites) : []), [sites]);
  const selected = sites?.find((s) => s.id === selectedId) ?? null;
  const states = useMemo(() => [...new Set(sites?.map((s) => s.stateName) ?? [])], [sites]);

  const onMarkerKey = (event: KeyboardEvent<SVGGElement>, id: string) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      setSelectedId(id);
    }
  };

  return (
    <section className="mx-auto max-w-6xl px-4 py-14 sm:px-6 sm:py-20" aria-labelledby="trial-map-heading">
      <p className="text-[13px] font-medium text-leaf-700">Trial locations</p>
      <h2
        id="trial-map-heading"
        className="mt-3 max-w-3xl text-[28px] leading-tight font-semibold tracking-[-0.025em] text-ink sm:text-[36px]"
      >
        Maize trials across {states.length ? states.join(' and ') : 'the Corn Belt'}.
      </h2>
      <p className="mt-3 max-w-2xl text-[15px] leading-relaxed text-muted">
        Select a location to see what data exists there, then open its forecasts.
      </p>

      <div className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1.6fr)_minmax(17rem,0.62fr)] lg:items-stretch">
        <div className="rounded-2xl border border-line bg-surface p-3 sm:p-5">
          <svg
            viewBox={`0 0 ${US_MAP_SIZE.width} ${US_MAP_SIZE.height}`}
            role="group"
            aria-label="Map of the contiguous United States with the maize trial locations"
            className="h-auto w-full"
          >
            <g aria-hidden="true">
              {US_STATES.map((s) => (
                <path
                  key={s.id}
                  d={s.d}
                  fill={s.highlight ? '#E7ECE6' : '#EFEDE8'}
                  stroke={s.highlight ? '#CBD5CC' : C.surface}
                  strokeWidth={s.highlight ? 1.2 : 1}
                  strokeLinejoin="round"
                />
              ))}
            </g>
            {markers.map(({ site, x, y, label, leader }, i) => {
              const active = site.id === selectedId;
              const hot = active || site.id === hoverId;
              return (
                <g
                  key={site.id}
                  role="button"
                  tabIndex={0}
                  aria-pressed={active}
                  aria-label={`${site.name}, ${site.stateName}`}
                  onClick={() => setSelectedId(site.id)}
                  onKeyDown={(e) => onMarkerKey(e, site.id)}
                  onPointerEnter={() => setHoverId(site.id)}
                  onPointerLeave={() => setHoverId(null)}
                  className="cursor-pointer outline-none [&:focus-visible>circle:first-child]:stroke-leaf-600"
                >
                  <circle cx={x} cy={y} r={20} fill="transparent" strokeWidth={2} />
                  {leader && <line {...leader} stroke={C.faint} strokeWidth={1} />}
                  <motion.circle
                    cx={x}
                    cy={y}
                    initial={reduce ? false : { r: 0 }}
                    animate={{ r: hot ? 15 : 11 }}
                    transition={{ duration: 0.3, ease: EASE_OUT, delay: reduce ? 0 : 0.2 + i * 0.06 }}
                    fill={C.leaf100}
                    opacity={0.9}
                  />
                  <motion.circle
                    cx={x}
                    cy={y}
                    initial={reduce ? false : { r: 0 }}
                    animate={{ r: active ? 7.5 : 6 }}
                    transition={{ duration: 0.3, ease: EASE_OUT, delay: reduce ? 0 : 0.2 + i * 0.06 }}
                    fill={active ? C.leaf800 : C.leaf600}
                    stroke={C.surface}
                    strokeWidth={2}
                  />
                  <text
                    x={label.x}
                    y={label.y}
                    textAnchor={label.anchor}
                    fontSize={LABEL_FONT}
                    className={`font-medium ${active ? 'fill-ink' : 'fill-ink-soft'}`}
                    paintOrder="stroke"
                    stroke={C.surface}
                    strokeWidth={4}
                    strokeLinejoin="round"
                  >
                    {site.name}
                  </text>
                </g>
              );
            })}
          </svg>
          {failed && <p className="px-2 pb-2 text-[13px] text-muted">The trial locations could not be loaded.</p>}
        </div>

        <aside className="flex flex-col rounded-2xl border border-line bg-surface p-6" aria-live="polite">
          <p className="text-[11px] font-medium tracking-[0.08em] text-faint uppercase">Selected location</p>
          <AnimatePresence mode="wait" initial={false}>
            {selected ? (
              <motion.div
                key={selected.id}
                className="flex flex-1 flex-col"
                initial={{ opacity: 0, y: 6 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -6 }}
                transition={{ duration: 0.18, ease: EASE_OUT }}
              >
                <SitePanel site={selected} />
              </motion.div>
            ) : (
              <div className="ss-skeleton mt-4 h-56 rounded-lg" />
            )}
          </AnimatePresence>
        </aside>
      </div>
    </section>
  );
}

function Availability({ ok, label, detail }: { ok: boolean; label: string; detail: string }) {
  return (
    <li className="flex items-start gap-2.5">
      <span
        className={`mt-0.5 flex h-5 w-5 shrink-0 items-center justify-center rounded-full ${ok ? 'bg-leaf-50 text-leaf-700' : 'bg-mist text-faint'}`}
        aria-hidden="true"
      >
        {ok ? <Check className="h-3 w-3" strokeWidth={3} /> : <Minus className="h-3 w-3" strokeWidth={3} />}
      </span>
      <span>
        <span className={`block text-[14px] font-medium ${ok ? 'text-ink' : 'text-muted'}`}>{label}</span>
        <span className="block text-[12px] text-muted">{detail}</span>
      </span>
    </li>
  );
}

function SitePanel({ site }: { site: TrialSite }) {
  const season = site.seasons[site.seasons.length - 1];
  const satellite = season?.satellite;
  const uav = season?.uav;
  const forecasts = hasForecasts(site);
  return (
    <>
      <h3 className="mt-3 text-[26px] font-semibold tracking-[-0.025em] text-ink">{site.name}</h3>
      <p className="text-[15px] text-muted">{site.stateName}</p>

      <dl className="mt-5 grid grid-cols-2 gap-3 border-t border-line pt-4 text-[14px]">
        <div>
          <dt className="text-muted">Crop</dt>
          <dd className="font-medium text-ink">{site.crop}</dd>
        </div>
        <div>
          <dt className="text-muted">Season</dt>
          <dd className="data font-medium text-ink">{site.seasons.map((s) => s.year).join(', ') || '—'}</dd>
        </div>
        {season && (
          <div>
            <dt className="text-muted">Trial plots</dt>
            <dd className="data font-medium text-ink">{formatNumber(season.plots)}</dd>
          </div>
        )}
        <div>
          <dt className="text-muted">Water</dt>
          <dd className="font-medium text-ink">{site.irrigated ? 'Irrigated' : 'Rainfed'}</dd>
        </div>
      </dl>

      <ul className="mt-5 space-y-3 border-t border-line pt-4">
        <Availability
          ok={!!satellite && satellite.plotImages > 0}
          label={satellite && satellite.plotImages > 0 ? 'Satellite imagery available' : 'No satellite plot imagery'}
          detail={
            satellite && satellite.plotImages > 0
              ? `${satellite.acquisitions} passes, ${formatNumber(satellite.plotImages)} plot images`
              : 'Not in the challenge data for this site'
          }
        />
        <Availability
          ok={!!uav && uav.plotImages > 0}
          label={uav && uav.plotImages > 0 ? 'UAV imagery available' : 'No UAV imagery'}
          detail={
            uav && uav.plotImages > 0
              ? `${uav.acquisitions} flights, ${formatNumber(uav.plotImages)} plot images`
              : 'Optional; not collected here'
          }
        />
        <Availability
          ok={!!site.weather}
          label={site.weather ? 'Weather history available' : 'No weather history'}
          detail={
            site.weather
              ? `${site.weather.seasons} seasons, ${site.weather.firstSeason}–${site.weather.lastSeason}`
              : 'Not loaded on this server'
          }
        />
      </ul>

      <div className="mt-auto pt-6">
        <Link
          to="dashboard"
          query={{ site: site.id, plot: null }}
          className={`lift group inline-flex w-full items-center justify-center gap-2 rounded-full px-5 py-2.5 text-[15px] font-medium ${
            forecasts
              ? 'bg-leaf-700 text-white hover:bg-leaf-800 hover:shadow-lift'
              : 'border border-line-strong text-ink hover:border-faint'
          }`}
        >
          {forecasts ? 'View forecasts' : 'Open location'}
          <ArrowRight className="h-4 w-4 transition-transform duration-200 group-hover:translate-x-0.5" />
        </Link>
        {!forecasts && <p className="mt-2 text-center text-[12px] text-muted">Plot forecasts arrive with the final results.</p>}
      </div>
    </>
  );
}
