/**
 * Generates src/components/overview/usMap.ts: simplified outlines of the contiguous U.S.
 * states as SVG paths (Albers equal-area, the standard U.S. map projection) plus the
 * projection constants the site markers use. The website then draws the map with no map
 * library and no tile service.
 *
 *   npm i --no-save us-atlas@3 topojson-client@3 topojson-simplify@3 d3-geo@3
 *   node scripts/build-us-map.mjs
 *
 * (or point MAP_DEPS at a folder where those packages are installed). Source: us-atlas
 * (U.S. Census Bureau cartographic boundaries, 1:10m), public domain.
 */

import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const require = createRequire(process.env.MAP_DEPS ? `${process.env.MAP_DEPS.replace(/\/$/, '')}/` : import.meta.url);
const topojson = require('topojson-client');
const { presimplify, quantile, simplify } = require('topojson-simplify');
const d3 = require('d3-geo');
const us = require('us-atlas/states-10m.json');

const WIDTH = 960;
const HEIGHT = 600;
const PAD = 8;
// Alaska, Hawaii and the territories are left out: the trial sites are all in the Corn Belt.
const EXCLUDE = new Set(['02', '15', '60', '66', '69', '72', '78']);
const HIGHLIGHT = new Set(['19', '31']); // Iowa, Nebraska

const pre = presimplify(us);
const simplified = simplify(pre, quantile(pre, 0.12));
const states = topojson
  .feature(simplified, simplified.objects.states)
  .features.filter((f) => !EXCLUDE.has(f.id));

const PARALLELS = [29.5, 45.5];
const ROTATE = 96;
const CENTER = [-0.6, 38.7];
const projection = d3
  .geoConicEqualArea()
  .parallels(PARALLELS)
  .rotate([ROTATE, 0])
  .center(CENTER)
  .fitExtent(
    [
      [PAD, PAD],
      [WIDTH - PAD, HEIGHT - PAD],
    ],
    { type: 'FeatureCollection', features: states },
  );
const path = d3.geoPath(projection).digits(1);

// The same projection written out, so the frontend can place markers without d3.
const scale = projection.scale();
const [tx, ty] = projection.translate();
const rad = Math.PI / 180;
function project(lon, lat) {
  const sy0 = Math.sin(PARALLELS[0] * rad);
  const n = (sy0 + Math.sin(PARALLELS[1] * rad)) / 2;
  const c = 1 + sy0 * (2 * n - sy0);
  const r0 = Math.sqrt(c) / n;
  const raw = (l, p) => {
    const r = Math.sqrt(c - 2 * n * Math.sin(p)) / n;
    return [r * Math.sin(l * n), r0 - r * Math.cos(l * n)];
  };
  const [cx, cy] = raw(CENTER[0] * rad, CENTER[1] * rad);
  const [x, y] = raw((lon + ROTATE) * rad, lat * rad);
  return [tx + scale * (x - cx), ty - scale * (y - cy)];
}
for (const [lon, lat] of [
  [-93.73, 42.01],
  [-103.7, 41.95],
  [-91.49, 41.2],
]) {
  const a = projection([lon, lat]);
  const b = project(lon, lat);
  if (Math.hypot(a[0] - b[0], a[1] - b[1]) > 0.01) throw new Error(`projection mismatch at ${lon},${lat}`);
}

const out = states
  .map((f) => ({ id: f.id, name: f.properties.name, d: path(f), highlight: HIGHLIGHT.has(f.id) }))
  .sort((a, b) => a.name.localeCompare(b.name));

const ts = `/**
 * Contiguous U.S. state outlines for the trial-site map (Albers equal-area, ${WIDTH}×${HEIGHT}).
 * Generated by scripts/build-us-map.mjs from us-atlas (U.S. Census Bureau, public domain);
 * do not edit by hand.
 */

export const US_MAP_SIZE = { width: ${WIDTH}, height: ${HEIGHT} } as const;

export interface StateShape {
  id: string; // FIPS code
  name: string;
  d: string;
  highlight: boolean; // a state with trial sites
}

export const US_STATES: StateShape[] = ${JSON.stringify(out)};

/** Projection constants matching the outlines above. */
const P = { parallels: [${PARALLELS.join(', ')}], rotate: ${ROTATE}, center: [${CENTER.join(', ')}], scale: ${scale.toFixed(4)}, translate: [${tx.toFixed(4)}, ${ty.toFixed(4)}] } as const;

/** [longitude, latitude] in degrees → map coordinates. */
export function projectLonLat(lon: number, lat: number): [number, number] {
  const rad = Math.PI / 180;
  const sy0 = Math.sin(P.parallels[0] * rad);
  const n = (sy0 + Math.sin(P.parallels[1] * rad)) / 2;
  const c = 1 + sy0 * (2 * n - sy0);
  const r0 = Math.sqrt(c) / n;
  const raw = (l: number, p: number): [number, number] => {
    const r = Math.sqrt(c - 2 * n * Math.sin(p)) / n;
    return [r * Math.sin(l * n), r0 - r * Math.cos(l * n)];
  };
  const [cx, cy] = raw(P.center[0] * rad, P.center[1] * rad);
  const [x, y] = raw((lon + P.rotate) * rad, lat * rad);
  return [P.translate[0] + P.scale * (x - cx), P.translate[1] - P.scale * (y - cy)];
}
`;

const target = fileURLToPath(new URL('../src/components/overview/usMap.ts', import.meta.url));
writeFileSync(target, ts);
console.log(`wrote ${out.length} states, ${(ts.length / 1024).toFixed(1)} KB → ${target}`);
